export let lite = [
  {
    id: 1,
    name: "Lite-Model Blue",
    color: "#3e5965",
    color1: "#c3d9e3",
    color2: "#a9c9d9",
    price: "Rs.14,000",
    reviews: 10,
    rating: 5,
    image: "/image/liteblue.jpg",
    images: [
      "/image/liteblue.jpg",
      "/image/liteblue2.jpg",
      "/image/liteblue3.jpg",
      "/image/liteblue4.jpg",
      "/image/litebluech.jpg",
    ],
  },
  {
    id: 2,
    name: "Lite-Model Green",
    color: "#397764",
    color1: "#70a592",
    color2: "#4d7c68",
    price: "Rs.14,100",
    reviews: 20,
    rating: 5,
    image: "/image/litegreen.jpg",
    images: [
      "/image/litegreen.jpg",
      "/image/litegreen2.jpg",
      "/image/litegreen3.jpg",
      "/image/litegreen4.jpg",
      "/image/litegreench.jpg",
    ],
  },
  {
    id: 3,
    name: "Lite-Model Rose Gold",
    color: "#d19ca1",
    color1: "#E8C2CA",
    color2: "#D0A0A5",
    price: "Rs.14,170",
    reviews: 15,
    rating: 4.5,
    image: "/image/litepink.jpg",
    images: [
      "/image/litepink.jpg",
      "/image/litepink2.jpg",
      "/image/litepink3.jpg",
      "/image/litepink4.jpg",
      "/image/litepinkch.jpg",
    ],
  },
  {
    id: 4,
    name: "Lite-Model Silver",
    color: "#e4e5e6",
    color1: "#ffffff",
    color2: "#B1B1B1",
    price: "Rs.14,230",
    reviews: 10,
    rating: 5,
    image: "/image/litewhite.jpg",
    images: [
      "/image/litewhite.jpg",
      "/image/litewhite2.jpg",
      "/image/litewhite3.jpg",
      "/image/litewhite4.jpg",
      "/image/litewhitech.jpg",
    ],
  },
  {
    id: 5,
    name: "Lite-Model Brown",
    color: "#654A4D",
    color1: "#a3744da1",
    color2: "#7a503de0",
    price: "Rs.14,000",
    reviews: 10,
    rating: 5,
    image: "/image/litebrown.jpg",
    images: [
      "/image/litebrown.jpg",
      "/image/litebrown2.jpg",
      "/image/litebrown3.jpg",
      "/image/litebrown4.jpg",
      "/image/litebrownch.jpg",
    ],
  },
];