export let model = [
  {
      id: 1,
      link: "/Promodel/",
      name: "Pro-Model Rings",
      price: "Rs.35,000 PKR",
      reviews: 10,
      rating: 5,
      image: "/protegoring.jpg",
      images: [
      "/image/problue.jpg",
      "/image/progreen.jpg",
      "/image/propink.jpg",
      "/image/prowhite.jpg",
      "/image/probrown.jpg",
    ],
    },
    {
      id: 2,
      link: "/Litemodel/",
      name: "Lite-Model Rings",
      price: "Rs.22,000 PKR",
      reviews: 20,
      rating: 5,
      image: "/protegoring.jpg",
      images: [
      "/image/liteblue.jpg",
      "/image/litegreen.jpg",
      "/image/litepink.jpg",
      "/image/litewhite.jpg",
      "/image/litebrown.jpg",
    ],
    },
    {
      id: 3,
      link: "/Stdmodel/",
      name: "Student-Model Rings",
      price: "Rs.2,124 PKR",
      reviews: 15,
      rating: 4.5,
      image: "/protegoring.jpg",
      images: [
      "/image/stdblue.jpg",
      "/image/stdgreen.jpg",
      "/image/stdpink.jpg",
      "/image/stdwhite.jpg",
      "/image/stdbrown.jpg",
    ],
    },
];