export let pro = [
  {
    id: 1,
    name: "Pro-Model Blue",
    color: "#3e5965",
    color1: "#c3d9e3",
    color2: "#a9c9d9",
    price: "Rs.18,000",
    reviews: 10,
    rating: 5,
    image: "/image/problue.jpg",
    images: [
      "/image/problue.jpg",
      "/image/problue2.jpg",
      "/image/problue3.jpg",
      "/image/problue4.jpg",
      "/image/probluech.jpg",
    ],
  },
  {
    id: 2,
    name: "Pro-Model Green",
    color: "#397764",
    color1: "#70a592",
    color2: "#4d7c68",
    price: "Rs.18,100",
    reviews: 20,
    rating: 5,
    image: "/image/progreen.jpg",
    images: [
      "/image/progreen.jpg",
      "/image/progreen2.jpg",
      "/image/progreen3.jpg",
      "/image/progreen4.jpg",
      "/image/progreench.jpg",
    ],
  },
  {
    id: 3,
    name: "Pro-Model Pink",
    color: "#d19ca1",
    color1: "#E8C2CA",
    color2: "#D0A0A5",
    price: "Rs.18,170",
    reviews: 15,
    rating: 4.5,
    image: "/image/propink.jpg",
    images: [
      "/image/propink.jpg",
      "/image/propink2.jpg",
      "/image/propink3.jpg",
      "/image/propink4.jpg",
      "/image/propinkch.jpg",
    ],
  },
  {
    id: 4,
    name: "Pro-Model Silver",
    color: "#e4e5e6",
    color1: "#ffffff",
    color2: "#B1B1B1",
    price: "Rs.18,230",
    reviews: 10,
    rating: 5,
    image: "/image/prowhite.jpg",
    images: [
      "/image/prowhite.jpg",
      "/image/prowhite2.jpg",
      "/image/prowhite3.jpg",
      "/image/prowhite4.jpg",
      "/image/prowhitech.jpg",
    ],
  },
  {
    id: 5,
    name: "Pro-Model Brown",
    color: "#654A4D",
    color1: "#a3744da1",
    color2: "#7a503de0",
    price: "Rs.18,000",
    reviews: 10,
    rating: 5,
    image: "/image/probrown.jpg",
    images: [
      "/image/probrown.jpg",
      "/image/probrown2.jpg",
      "/image/probrown3.jpg",
      "/image/probrown4.jpg",
      "/image/probrownch.jpg",
    ],
  },
];