export let std = [
  {
    id: 1,
    name: "Student-Model Blue",
    color: "#3e5965",
    color1: "#c3d9e3",
    color2: "#a9c9d9",
    price: "Rs.10,000",
    reviews: 10,
    rating: 5,
    image: "/image/stdblue.jpg",
    images: [
      "/image/stdblue.jpg",
      "/image/stdblue2.jpg",
      "/image/stdblue3.jpg",
      "/image/stdblue4.jpg",
      "/image/stdbluech.jpg",
    ],
  },
  {
    id: 2,
    name: "Student-Model Green",
    color: "#397764",
    color1: "#70a592",
    color2: "#4d7c68",
    price: "Rs.10,100",
    reviews: 20,
    rating: 5,
    image: "/image/litegreen.jpg",
    images: [
      "/image/stdgreen.jpg",
      "/image/stdgreen2.jpg",
      "/image/stdgreen3.jpg",
      "/image/stdgreen4.jpg",
      "/image/stdgreench.jpg",
    ],
  },
  {
    id: 3,
    name: "Student-Model Pink",
    color: "#d19ca1",
    color1: "#E8C2CA",
    color2: "#D0A0A5",
    price: "Rs.10,170",
    reviews: 15,
    rating: 4.5,
    image: "/image/stdpink.jpg",
    images: [
      "/image/stdpink.jpg",
      "/image/stdpink2.jpg",
      "/image/stdpink3.jpg",
      "/image/stdpink4.jpg",
      "/image/stdpinkch.jpg",
    ],
  },
  {
    id: 4,
    name: "Student-Model Silver",
    color: "#e4e5e6",
    color1: "#ffffff",
    color2: "#B1B1B1",
    price: "Rs.10,230",
    reviews: 10,
    rating: 5,
    image: "/image/stdwhite.jpg",
    images: [
      "/image/stdwhite.jpg",
      "/image/stdwhite2.jpg",
      "/image/stdwhite3.jpg",
      "/image/stdwhite4.jpg",
      "/image/stdwhitech.jpg",
    ],
  },
  {
    id: 5,
    name: "Student-Model Brown",
    color: "#654A4D",
    color1: "#a3744da1",
    color2: "#7a503de0",
    price: "Rs.10,000",
    reviews: 10,
    rating: 5,
    image: "/image/stdbrown.jpg",
    images: [
      "/image/stdbrown.jpg",
      "/image/stdbrown2.jpg",
      "/image/stdbrown3.jpg",
      "/image/stdbrown4.jpg",
      "/image/stdbrownch.jpg",
    ],
  },
];